# ============================================
# Zhejian Wang - Academic Job Market Website
# Based on academicpages template
# ============================================

# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Zhejian Wang - Economics Ph.D. Candidate"
title_separator: "-"
name: &name "Zhejian Wang"
description: &description "Economics Ph.D. Candidate at the University of Delaware"
url: "https://zhejianw.github.io"
baseurl: ""
repository: "zhejianw/zhejianw.github.io"

# Sidebar Author Information
author:
  avatar: "19.jpg"
  name: "Zhejian Wang"
  pronouns: "he/him"
  bio: "Ph.D. Candidate in Economics at the University of Delaware. Research in development economics, education, and digital policy."
  location: "Newark, Delaware, USA"
  employer: "University of Delaware"
  email: "zhejianw@udel.edu"
  github: "zhejianw"


# Publication categories
publication_category:
  workingpapers:
    title: 'Working Papers'
  manuscripts:
    title: 'Publications'
  conferences:
    title: 'Conference Presentations'

# Site Settings
teaser: 
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: false

# RSS and Atom feed
atom_feed:
  hide: false

# SEO Related
social:
  type: "Person"
  name: "Zhejian Wang"
  links:
    - "https://scholar.google.com"
    - "https://www.linkedin.com/in/zhejianwang"
    - "https://github.com/zhejianw"

# Analytics
analytics:
  provider: false

# File Reading and Exclusions
include:
  - .htaccess
  - _pages
  - files
  - images
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - LICENSE
  - README
  - node_modules
  - tmp
  - vendor

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown and Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  toc_levels: 1..6

# Collections (content folders)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Default layouts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output and Plugins
permalink: /:categories/:title/
timezone: America/New_York
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
